/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.MySQL;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MSI
 */
public class dsladdissue extends javax.swing.JFrame {

    DateTimeFormatter dttf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    LocalDateTime now = LocalDateTime.now();
    String date = dttf.format(now);

    String tdyissuesid;

    DSLhome h;

    public dsladdissue() {
        initComponents();

        loadroute();
        loadvehicle();
    }

    public void loadvehicle() {

        try {
            ResultSet rs = MySQL.search("SELECT * FROM `vehicle` ");

            Vector v = new Vector();
            v.add("Select");

            while (rs.next()) {
                v.add(rs.getString("number"));
            }

            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void loadroute() {

        try {
            ResultSet rs = MySQL.search("SELECT * FROM `route` ");

            Vector v = new Vector();
            v.add("Select");

            while (rs.next()) {
                v.add(rs.getString("name"));
            }

            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);
            jComboBox13.setModel(dcm);
            //   jComboBox7.setModel(dcm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tdyissue = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        issuedte = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        ipname = new javax.swing.JLabel();
        iqty = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        iuprice = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        riqty = new javax.swing.JTextField();
        isprice = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel142 = new javax.swing.JLabel();
        irefname = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        irefid = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jButton23 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tdyissue.setBackground(new java.awt.Color(236, 253, 236));

        jPanel43.setBackground(new java.awt.Color(43, 90, 137));

        jLabel129.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(255, 255, 255));
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel129.setText("Add Today Issue Products | ");

        issuedte.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        issuedte.setForeground(new java.awt.Color(255, 255, 255));
        issuedte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issuedte.setText("2022/08/24");

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issuedte, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel129)
                .addComponent(issuedte, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel130.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel130.setText("Product Name :-");

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel131.setText("Available Quantity :-");

        jLabel132.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel132.setText("Issue Quantity :-");

        jButton14.setBackground(new java.awt.Color(0, 51, 255));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Add to The Table");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton14.setBorderPainted(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Id", "date", "product", "quantity", "selling price", "Reference Agent", "route"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jButton16.setBackground(new java.awt.Color(0, 153, 0));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Save Today Issues");
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 0, 153));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Select Product In Stock");
        jButton18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton18.setBorderPainted(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        ipname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ipname.setForeground(new java.awt.Color(102, 102, 102));
        ipname.setText("None");

        iqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iqty.setForeground(new java.awt.Color(102, 102, 102));
        iqty.setText("None");

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel136.setText("unit Price :-");

        iuprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iuprice.setForeground(new java.awt.Color(102, 102, 102));
        iuprice.setText("None");

        jLabel143.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel143.setText("Selling Price :-");

        jButton21.setBackground(new java.awt.Color(0, 0, 153));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Select Reference Agent ");
        jButton21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton21.setBorderPainted(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel142.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel142.setText("Ref Name :-");

        irefname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        irefname.setForeground(new java.awt.Color(102, 102, 102));
        irefname.setText("None");

        jLabel147.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel147.setText("Select Route :-");

        jLabel160.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel160.setText("Ref ID :-");

        irefid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        irefid.setForeground(new java.awt.Color(102, 102, 102));
        irefid.setText("None");

        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton23.setText("+");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tdyissueLayout = new javax.swing.GroupLayout(tdyissue);
        tdyissue.setLayout(tdyissueLayout);
        tdyissueLayout.setHorizontalGroup(
            tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tdyissueLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tdyissueLayout.createSequentialGroup()
                        .addComponent(jLabel130, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipname, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tdyissueLayout.createSequentialGroup()
                                .addGap(363, 363, 363)
                                .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel136, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                            .addGroup(tdyissueLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tdyissueLayout.createSequentialGroup()
                                        .addComponent(jLabel131, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iqty, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tdyissueLayout.createSequentialGroup()
                                        .addComponent(jLabel132, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(riqty, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iuprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isprice)))
                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tdyissueLayout.createSequentialGroup()
                        .addComponent(jLabel142, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irefname, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel160)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(irefid, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel147, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tdyissueLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                        .addGap(264, 264, 264)))
                .addGap(22, 22, 22))
        );
        tdyissueLayout.setVerticalGroup(
            tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tdyissueLayout.createSequentialGroup()
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(irefname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel160, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(irefid))
                        .addComponent(jLabel142))
                    .addComponent(jLabel147)
                    .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel136, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iuprice))
                    .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel131, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iqty))
                    .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel130)
                        .addComponent(ipname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tdyissueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel132)
                    .addComponent(jLabel143)
                    .addComponent(isprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tdyissue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tdyissue, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

        String pname = ipname.getText();
        String pqty = iqty.getText();
        String iqtyy = riqty.getText();
        String sprice = isprice.getText();
        String rid = irefid.getText();
        String refname = irefname.getText();
        String route = jComboBox13.getSelectedItem().toString();

        if (rid.equals("None")) {
            JOptionPane.showMessageDialog(this, "Please Select a Ref!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (route.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please Select a Route!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (pname.equals("None")) {
            JOptionPane.showMessageDialog(this, "First Select Product in Stock!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (iqtyy.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Add a Isuue Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Double.parseDouble(pqty) < Double.parseDouble(iqtyy)) {
            JOptionPane.showMessageDialog(this, "Check Quantity!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (sprice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Add a Selling Price!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            DefaultTableModel dtm = (DefaultTableModel) jTable5.getModel();

            Vector v = new Vector();
            v.add(tdyissuesid);
            v.add(date);
            v.add(pname);
            v.add(iqtyy);
            v.add(sprice);
            v.add(refname);
            v.add(route);

            dtm.addRow(v);

            ipname.setText("None");
            riqty.setText("");
            iqty.setText("None");
            iuprice.setText("0.00");
            isprice.setText("");

        }

    }//GEN-LAST:event_jButton14ActionPerformed


    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        String rid = irefid.getText();

        if (jTable5.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "please add a product to Issue Table", "warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                // ResultSet rrss1 = MySQL.search(" SELECT * FROM `vehicle` WHERE `number`='" + vnum + "' ");
                //rrss1.next();
                //String viid = rrss1.getString("id");
                for (int i = 0; i < jTable5.getRowCount(); i++) {

                    String sid = jTable5.getValueAt(i, 0).toString();
                    String Ddate = jTable5.getValueAt(i, 1).toString();
                    String pname = jTable5.getValueAt(i, 2).toString();

                    ResultSet rs = MySQL.search("SELECT * FROM `product` WHERE `pname`='" + pname + "' ");
                    rs.next();
                    String pid = rs.getString("id");

                    String qty = jTable5.getValueAt(i, 3).toString();
                    String selling_price = jTable5.getValueAt(i, 4).toString();
                    String route = jTable5.getValueAt(i, 6).toString();

                    ResultSet rs3 = MySQL.search("SELECT * FROM `route` WHERE `name`='" + route + "' ");
                    rs3.next();
                    String rouid = rs3.getString("id");

                    MySQL.iud("INSERT INTO `issue`(`date`,`product_id`,`qty`,`selling_price`,`stock_id`,`ref_id`,`route_id`,`status`)"
                            + " VALUES('" + Ddate + "','" + pid + "','" + qty + "','" + selling_price + "','" + sid + "','" + rid + "','" + rouid + "','1') ");

                    ResultSet rs4 = MySQL.search("SELECT * FROM `stock` WHERE `id`='" + sid + "' ");
                    rs4.next();
                    String aqty = rs4.getString("qty");

                    int newqt = Integer.parseInt(aqty) - Integer.parseInt(qty);

                    MySQL.iud("UPDATE `stock` SET `qty`='" + newqt + "' WHERE `id`='" + sid + "' ");

                    ResultSet vehi = MySQL.search("SELECT * FROM `vehistock` WHERE `product`='" + pid + "' AND `price`='" + selling_price + "'; ");

                    if (vehi.next()) {

                        String vehistockid = vehi.getString("id");

                        int vehiqty = Integer.parseInt(vehi.getString("qty"));
                        int iqty = Integer.parseInt(qty);
                        int newvqty = vehiqty + iqty;
                        String newvehiqty = String.valueOf(newvqty);

                        MySQL.iud("UPDATE `vehistock` SET `qty`='" + newvehiqty + "' WHERE `id`='" + vehistockid + "' ");

                    } else {

                        ResultSet vehinum = MySQL.search("SELECT * FROM `ref` WHERE `id`='" + rid + "' ");
                        vehinum.next();
                        String vehiid = vehinum.getString("vehicle");

                        MySQL.iud("INSERT INTO `vehistock`(`date`,`ref`,`vehicle`,`product`,`qty`,`price`,`stock`,`status`) "
                                + "VALUES('" + Ddate + "','" + rid + "','" + vehiid + "','" + pid + "','" + qty + "','" + selling_price + "','" + sid + "','1') ");

                    }

                }

                //  MySQL.iud("DELETE FROM `vehistock` WHERE `vehicle`='" + viid + "' ");
                JOptionPane.showMessageDialog(this, "Product Issue succesfull !", "Success", JOptionPane.INFORMATION_MESSAGE);

                // String daatte = issuedte.getText().toString();
                // String reeefname = irefname.getText().toString();
                // String rouutte = jComboBox13.getSelectedItem().toString();
                // JasperReport jr = JasperCompileManager.compileReport(getClass().getResourceAsStream("/reports/collection.jrxml"));
                //HashMap parameters = new HashMap();
                //parameters.put("date", daatte);
                //parameters.put("ref", reeefname);
                //parameters.put("route", rouutte);
                // JREmptyDataSource dataSource = new JREmptyDataSource();
                //TableModel tm = jTable5.getModel();
                //JRTableModelDataSource dataSource = new JRTableModelDataSource(tm);
                //Connection dataSource = MySQL.getConnection();
                //JasperPrint jp = JasperFillManager.fillReport(jr, parameters, dataSource);
                // JasperViewer.viewReport(jp, false);
                ipname.setText("None");
                riqty.setText("");
                iqty.setText("None");
                iuprice.setText("0.00");
                isprice.setText("");
                jComboBox13.setSelectedItem("Select");
                irefid.setText("None");
                irefname.setText("None");

                //table
                DefaultTableModel dtm = (DefaultTableModel) jTable5.getModel();
                dtm.setRowCount(0);
                //table

                h.loadissue();

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton16ActionPerformed

    String rid;

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:

        String rid = irefid.getText();

        if (rid.equals("None")) {
            JOptionPane.showMessageDialog(this, "please Select a ref first", "warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {

                ResultSet r = MySQL.search(" SELECT * FROM `r` ");

                if (r.next()) {

                    MySQL.iud("UPDATE `r` SET `num`='" + rid + "' WHERE `id`='1' ");

                } else {

                    MySQL.iud("INSERT INTO `r`(`id`,`num`) VALUES('1','" + rid + "') ");

                }

            } catch (Exception e) {
                e.printStackTrace();

            }

            searchstock1 sc = new searchstock1(this);
            sc.setVisible(true);

        }


    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            jButton21.setEnabled(true);

        }
    }//GEN-LAST:event_jButton21MouseClicked


    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:

        searchref sr = new searchref(this);
        sr.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:

        addroute ar = new addroute(this);
        ar.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {

            int r = jTable5.getSelectedRow();

            if (r == -1) {
                JOptionPane.showMessageDialog(this, "Please Select a row", "warning", JOptionPane.WARNING_MESSAGE);
            } else {

                String id = jTable5.getValueAt(r, 0).toString();

                int jd = JOptionPane.showOptionDialog(this, "Do you want delete this product in table", "warnning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Yes", "No"}, JOptionPane.YES_OPTION);

                if (jd == JOptionPane.YES_OPTION) {

                    DefaultTableModel model = (DefaultTableModel) this.jTable5.getModel();
                    model.removeRow(r);

                }

            }
        }

    }//GEN-LAST:event_jTable5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dsladdissue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dsladdissue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dsladdissue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dsladdissue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dsladdissue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ipname;
    public javax.swing.JLabel iqty;
    public javax.swing.JLabel irefid;
    public javax.swing.JLabel irefname;
    private javax.swing.JTextField isprice;
    private javax.swing.JLabel issuedte;
    public javax.swing.JLabel iuprice;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    public javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField riqty;
    private javax.swing.JPanel tdyissue;
    // End of variables declaration//GEN-END:variables
}
